### ISSUE TITLE
Error: Not valid bed12 file

### ISSUE THREAD

**Issue by katannyak** [YeoLab/clip_analysis_legacy#3]
Hi @byee4,
I'm trying to run the example for this package, using my own ref genome fasta file (including fa.fai) since the fasta file in the example/inputs folder points to something on TSCC. I get the following error indicating that the bed file (in bed6 format) should be in bed12 format. I've tried to troubleshoot this by added extra "." in tab-delim format to the example bed file (204_01.basedon_....Fc3Pv3.bed) create a bed12 file. But I still came to the same error. Any suggestions for troubleshooting this? Much thanks!

```
Not Valid bed12 file, continuing processing, some things may be strange, also this will cause a file leak in pybedtools, watch out
Traceback (most recent call last):
  File "/Users/katannya/opt/anaconda3/envs/motif-analysis/bin/analyze_motifs", line 11, in <module>
    load_entry_point('analyze-motifs==0.0.1', 'console_scripts', 'analyze_motifs')()
  File "/Users/katannya/opt/anaconda3/envs/motif-analysis/lib/python2.7/site-packages/analyze_motifs-0.0.1-py2.7.egg/clip_analysis_legacy/analyze_motifs.py", line 206, in call_main
    homer_outdir=args.out_homer_dir

File "/Users/katannya/opt/anaconda3/envs/motif-analysis/lib/python2.7/site-packages/analyze_motifs-0.0.1-py2.7.egg/clip_analysis_legacy/analyze_motifs.py", line 73, in main
    species=species, nrand=nrand)
  File "/Users/katannya/opt/anaconda3/envs/motif-analysis/lib/python2.7/site-packages/analyze_motifs-0.0.1-py2.7.egg/clip_analysis_legacy/CLIP_analysis.py", line 336, in assign_to_regions
    tool = tool.sort().merge(s=True, c="4,5,6,7,8", o="collapse,collapse,collapse,min,min").each(fix_strand_v26).saveas()
  File "/Users/katannya/opt/anaconda3/envs/motif-analysis/lib/python2.7/site-packages/pybedtools/bedtool.py", line 806, in decorated
    result = method(self, *args, **kwargs)
  File "/Users/katannya/opt/anaconda3/envs/motif-analysis/lib/python2.7/site-packages/pybedtools/bedtool.py", line 337, in wrapped
    decode_output=decode_output,
  File "/Users/katannya/opt/anaconda3/envs/motif-analysis/lib/python2.7/site-packages/pybedtools/helpers.py", line 356, in call_bedtools
    raise BEDToolsError(subprocess.list2cmdline(cmds), stderr)
pybedtools.helpers.BEDToolsError: 
Command was:

	bedtools sort -i /var/folders/yr/hkywcm7102lgslr0pnnlt4z40000gn/T/pybedtools.Y26YIA.tmp

Error message was:
libc++abi: terminating with uncaught exception of type std::invalid_argument: stoll: no conversion

```

**Comment by byee4** [comment]
Haven't seen this one before. But I wonder if you try using bedtools 2.26.0 and pybedtools 0.8.0 that it would work? Those are the versions that should work

**Comment by katannyak** [comment]
cool! Thanks Brian. Something's working now. I had the wrong version of pybedtools 0.8.0...perhaps you could update the readme and create_environment.sh with this version? Thanks :)

**Comment by byee4** [comment]
Thanks Katannya! Just updated the reqs. https://github.com/YeoLab/clip_analysis_legacy/commit/3d03fe293aad932fcb487cb1fa939acaa69de82e
